cargo-features = ["resolver"]

[package]
name = "shooter"
version = "0.1.0"
authors = ["August"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
heron = "0.5.1"

# cargo run --features bevy/dynamic
